### ISSUE TITLE
Musket, Crossbow and Blunderbust's duration is way too low for the resources used. 

### ISSUE THREAD

**Issue by Herkras** [TheOnlySilverClaw/Reforged#184]
Title. 

They dont do enough damage to justify their construction either since a vanilla bow does 6-10 damage in a more quick succession.

**Comment by thibeinn** [comment]
This part for the musket (also includes the blunderbuss) in the configuration file is confusing...

    # Damage of the Musket [range: 1.0 ~ 50.0, default: 10.0]
    S:"Musket Damage"=10.0

Set to the default of 10.0, you must be at least 11 blocks away from an animal/monster in order for your shots to hit it.  In order to hit an animal/monster at a closer distance you have to lower the number (example: change 10.0 to 5.0). Now you can hit animals/monsters from 6+ blocks away, but your damage is reduced (it takes more shots to kill).  If you change the default from 10.0 to say 25.0 so your shots do more damage, you now must be a minimum of 26 blocks from the animal/monster in order to hit it.  This reveals that both hitting distance and damage are combined into this one setting.  That doesn't make sense. Please make it so we can change both hitting distance and damage separately.

Thank you.

**Comment by ThexXTURBOXx** [comment]
As @thibeinn said, you can change the damage in the config
