### ISSUE TITLE
I can continue this project (read description)

### ISSUE THREAD

**Issue by TurkishAhmet4545** [TheOnlySilverClaw/Reforged#199]
I can continue this project but i can only make the items and ingredients.I can't make effects or do scripts.

**Comment by ThexXTURBOXx** [comment]
That sounds nice!
The mod doesn't have much effects anyway and you don't need scripts.
Just fork this project and open a PR. I will merge it then and when you ask me to do so, I will build a release and upload it to CurseForge.
When I see, that I can trust you, I will add you as a contributor to this project (sorry, that I have to do it like this, but I have been betrayed a few times in the past, so I don't trust anybody since then).
If you are still interested, then you can just go ahead and port the mod to 1.13 or finish my port (in the 1.13 branch) or just add some features or do something else.
I am very happy right now, that someone wants to continue this project :)

**Comment by TurkishAhmet4545** [comment]
How can i fork this project ?

**Comment by ThexXTURBOXx** [comment]
You just have to click on the "Fork" icon in the upper right of this page

**Comment by TurkishAhmet4545** [comment]
Ok.But i want to add 3D guns(for example: M4A1,deagle etc.) and keybinds.How can i do this ?

**Comment by TurkishAhmet4545** [comment]
And i want to ask one more question : How can i translate the mod ?

**Comment by ThexXTURBOXx** [comment]
This mod isn't really made for modern weapons. It's divided into 3 stages: Primitive, Medieval and Gunpowder
If you want modern weapons, then you should go e.g. to Flan's mod and write a content pack.
I also can't really teach you coding and modeling, because I halted this project for the same reason: I don't have much time next to university.
If you want to continue this project, then you have to learn all that stuff yourself, as I did.

Translating is described here: https://github.com/ThexXTURBOXx/Reforged#translation

**Comment by TurkishAhmet4545** [comment]
Ok.I think i can just custom some textures and translate the mod.Because im going to 6th grade and i can't learn coding and modeling.Thanks for answering my questions.

**Comment by TurkishAhmet4545** [comment]
I think i don't need to ask more questions.Thanks for your helps.

**Comment by ThexXTURBOXx** [comment]
Okay, no problem.
But trust me: You are never too young to learn coding ;)

**Comment by TurkishAhmet4545** [comment]
I have one more question : Can i make my update for 1.12.2 ? because it's my favorite version.

**Comment by ThexXTURBOXx** [comment]
The main branch is the 1.12.2 branch. You can build the mod yourself without my help, too.
Just run "gradlew build" and then copy the mod jar out of build/libs

**Comment by TurkishAhmet4545** [comment]
I have one more question : What is "$1" or "$2" in the translating files ?

I know im asking so much questions but if i don't learn these my mod can't work.

**Comment by ThexXTURBOXx** [comment]
Just don't worry about these. They will get replaced in Minecraft by Player names and so on.

**Comment by TurkishAhmet4545** [comment]
I did done the update.I can upload my file but i think im writed somethings false.I hope my mod work.
Where will i upload my file ?

**Comment by TurkishAhmet4545** [comment]
[Reforged-1.12.2.zip](https://github.com/ThexXTURBOXx/Reforged/files/3747181/Reforged-1.12.2.zip)
this is the mod file.

**Comment by TurkishAhmet4545** [comment]
Im just translated the mod in my update only.

**Comment by ThexXTURBOXx** [comment]
Yes, there seems to be something wrong.
The strings before the "=" may not be replaced by anything and you should not remove any linebreaks.

**Comment by TurkishAhmet4545** [comment]
How can i fix ?

**Comment by TurkishAhmet4545** [comment]
do i need to write the translation again ? If i need to write the translation again,i can.

**Comment by TurkishAhmet4545** [comment]
Can i remove $1 and $2 in my translation file ?

**Comment by ThexXTURBOXx** [comment]
It looks like, you need to write it again. Just take [this file](https://raw.githubusercontent.com/ThexXTURBOXx/Reforged/1.12/src/main/resources/assets/reforged/lang/en_gb.lang) and translate everything after the "=" signs.
Don't remove any linebreaks, don't remove any $1 and $2 and don't change anything before the "=" signs or else, you will break the mod.
When you are done, upload just this one file and I will review it again

**Comment by TurkishAhmet4545** [comment]
Can $1 or $2 stay anywhere between equals or dot ?

**Comment by ThexXTURBOXx** [comment]
No, they need to be placed in the right place.
For example:
%1$s got sliced by a bolt while fighting %2$s.

Then %1$s gets replaced by the name of the victim and %2$s gets replaced by the name of the killer.
So, you have to place them, where those names should stand.

Another example:
%1$s got sliced by a bolt.

Here, %1$s is the only thing in there and will be replaced by the name of the victim, because there is no known killer.

**Comment by TurkishAhmet4545** [comment]
Do you mean %$1 and %$2's place doesn't need to be changed in any language ?

If you don't mean this,im not gonna translate the writings that have $1 or $2.

**Comment by ThexXTURBOXx** [comment]
That depends on how your language is formed. In English, I could have also written the following:
While fighting %2$s, %1$s got sliced by a bolt.
So, you need to place them right.

I am sorry, but I think, that this whole thing doesn't make sense, if you can't do that.

**Comment by TurkishAhmet4545** [comment]
But i don't know where do i need to place the %$1 or %$2 in turkish language.

I can place them to false place.

**Comment by ThexXTURBOXx** [comment]
Just imagine replacing %2$s with "the killer" and %1$s with "the victim".
For example, then translate:
The victim got sliced by a bolt while fighting the killer.
to turkish. Let me take Google Translator's string here:
Kurban katille savaşırken bir cıvata ile dilimlenmiş.
Then replace "Kurban" with %1$s and "katille" with %2$s again, so you get:
%1$s %2$s savaşırken bir cıvata ile dilimlenmiş.
And that's what you write there

**Comment by TurkishAhmet4545** [comment]
Ok,Thanks.

**Comment by TurkishAhmet4545** [comment]
Thank you for giving the translating file as a list btw.It helped me alot.

**Comment by TurkishAhmet4545** [comment]
Do i need to translate "player" word ?

**Comment by TurkishAhmet4545** [comment]
Did i writed this true ? :

death.attack.boomerang.player=Bumerang %1$s ile %2$s oyuncuya saldırıldı.

**Comment by TurkishAhmet4545** [comment]
Please don't answer 2 questions in same message because if you answer 2 questions in same message i can't understand.

**Comment by ThexXTURBOXx** [comment]
> 
> 
> Do i need to translate "player" word ?

No. As I said before, **DON'T** change **anything** before the equal sign.


> 
> 
> Did i writed this true ? :
> 
> death.attack.boomerang.player=Bumerang %1$s ile %2$s oyuncuya saldırıldı.

I don't know turkish, but Google translator told me, that this isn't a direct translation of the english words. You need to _translate_ it, not write own things.


I am sorry, but this whole thing doesn't work out.
Learn all the mandatory things for modding and translating first and then you can try again.
Also, learn the basics of Github, so you can send me the translation file like every other one did (e.g. #145).
After that, you are invited to try again, but until then, I have to do much work for the university, so I can't "babysit" your work here.

**Comment by TurkishAhmet4545** [comment]
I think i can't do anything.Im cancelling to continue this project.Im very sorry for distributing you.Please forgive me.😭😭
