### ISSUE TITLE
Fabric Revival

### ISSUE THREAD

**Issue by TheOnlySilverClaw** [TheOnlySilverClaw/Reforged#203]
Hey guys,

since I currently don't have much else to do, I started playing Minecraft again and I was already missing a well-balanced weapon mod, so I thought to dig this one up again.
I'm planning to work with the [Fabric](https://fabricmc.net/) Mod Loader for the newer Minecraft version (currently 15.2), since that seems to be more developer-friendly than Forge, even though missing some advanced features at the moment.

Anyway, I wanted to ask if anyone objects to me "recycling" the resources and basic structure from this project after being absent for so long. I probably won't do a 1:1 port, since a lot of combat mechanics have changed in the meantime.

**Comment by ThexXTURBOXx** [comment]
Hey, long time no hear!

You certainly have my permission to use the code in this repo. Much of the code also is still from you.
And I think, you also may take the resources, because the artists gave you the permission to use them back then, but I am not sure about that.

Also, I noticed that your Curseforge account somehow got renamed or something. If you plan to publish new releases, even on a totally new code base, I can readd you on Reforged's project page, so you can release them there, because it already has some publicity.
You could name them Reforged 2 or something. But if you want, you can also create a totally new project on Curseforge, that's up to you :)

Interestingly enough, my friends asked me about this mod for a while now and are asking if I wanted to continue working on it or port it to Fabric, but I don't have too much time next to studying as I study maths and computer science at the same time. But if I find time, I will definetly continue developing this mod or your rewrite further (as I wanted to rewrite it for a long time now).

But be aware when taking the code from this repo:
Many parts. No... Major parts don't have any code style, are inefficient or unsafe. When I look back at this code, I almost have to throw up :D

That said, have fun and see you soon when and if I have enough time!

**Comment by TheOnlySilverClaw** [comment]
Yeah, since Fabric uses a lot of different function names, class naming conventions, etc., I will have to rewrite most of the code anyway, so I will not retain the old unsafe and inefficient parts, but create my own unsafe and inefficient ones ;)
But considering that a lot of the ugly stuff was forced upon us by Minecraft and Forge, it's actually not that bad. At least for the items I started with, I had no trouble figuring out what it was supposed to do. But I guess you're talking about the more advanced stuff.
At the least, Fabric seems to have better official documentation, so it's easier to get things done "the right way".

About publishing, I'm still not sure. Apparently, CurseForge switched to using Twitch accounts and I never migrated my account. I'm still pondering whether I want to create one, but you're right, it might help a lot of people actually finding the new releases, so I probably will do so eventually...

And of course I'd love to have explicit permission from @SnowballFlame to use the textures before releasing anything.

**Comment by ThexXTURBOXx** [comment]
Okay, very nice ;)

Yes, the Forge API is terrible, as many people already pointed out (including me).
The advanced stuff is even more terrible. Big **F**.

Regarding the publishing: If you want, I can just upload them for you, if you don't want to create a Twitch Account. That would be no problem for me, as it doesn't take much time (I just have to upload the files and add the changelog).
If you would like to create a new project, then I could just link to that one in Reforged's description, but I think, that not that many people will find it then. But that's your decision to make :)

Edit: Also, I see that you still have access to this repository. If you want, you can create your own branch here and develop in there. But you can also create a new repo, which I will link to in the Sources tab on CurseForge. That's also your decision to make :D

**Comment by TheOnlySilverClaw** [comment]
I was also thinking about moving my code from my current repository to a branch of this one.
I'll check how much sense that makes with Git when the codebase ends up having large differences.

Regarding the CurseForge project, I will have to consider that... there seem to be both approaches right now. Making a separate project for Forge and Fabric versions as well as using one project for both releases. The latter ones seem to usually end up getting comments from disappointed Forge users for not actually supporting the version they were looking for.

So, yeah... actually not sure what to do about the organizational issues right now. Let's get some coding done first. :)

**Comment by ThexXTURBOXx** [comment]
Okay. Yes, I have seen some people doing such things. It doesn't seem like it is a major problem though, as long as you don't compare - or even worse: merge - across these branches.

That's a good point, though. Most people have 2 separate releases, one labeled "-forge" and one "-fabric" for that specific reason. We could do the same and also add the "Fabric" category to Reforged itself. I think, Fabric doesn't work with anything up to 1.12.2 (please correct me if I am mistaken), so there won't be anyone, that could mistake the old releases for Fabric ones then, I guess...

Yes, get some coding done first and then we can talk again :) Also be sure to make it open source as soon as possible, so I might create some PRs or addons or something as well if I find some time next to university (digital study sucks btw) :)

**Comment by Squeekblach** [comment]
You still have my permission to use the textures as always. I can create or modify more if needed, just mention me here.

**Comment by TheOnlySilverClaw** [comment]
I assumed that, I just wanted to make sure after such a long time.
And thanks for the offer, I might actually come back on that.

**Comment by ThexXTURBOXx** [comment]
If someone sees this issue, there is also this: https://github.com/ThexXTURBOXx/Reforged-Modernized
It provides functionality for both Forge and Fabric simultaneously. However, I did not implement most weapons yet

**Comment by ThexXTURBOXx** [comment]
See #217 :)
